# stack exec GenesisNF ~/nofib/imaginary/bernouilli 1 1 1 >> gennofib.log 2>&1 ;
# stack exec GenesisNF ~/nofib/imaginary/exp3_8 1 1 1 >> gennofib.log 2>&1 ;
stack exec GenesisNF ~/nofib/imaginary/gen_regexps 1 1 1 >> gennofib.log 2>&1 ;
# stack exec GenesisNF ~/nofib/imaginary/integrate 1 1 1 >> gennofib.log 2>&1 ;
# stack exec GenesisNF ~/nofib/imaginary/kahan 1 1 1 >> gennofib.log 2>&1 ;
# stack exec GenesisNF ~/nofib/imaginary/paraffins 1 1 1 >> gennofib.log 2>&1 ;
# stack exec GenesisNF ~/nofib/imaginary/primes 1 1 1 >> gennofib.log 2>&1 ;
# stack exec GenesisNF ~/nofib/imaginary/queens 1 1 1 >> gennofib.log 2>&1 ;
# stack exec GenesisNF ~/nofib/imaginary/rfib 1 1 1 >> gennofib.log 2>&1 ;
# stack exec GenesisNF ~/nofib/imaginary/tak 1 1 1 >> gennofib.log 2>&1 ;
# stack exec GenesisNF ~/nofib/imaginary/wheel-sieve1 1 1 1 >> gennofib.log 2>&1 ;
stack exec GenesisNF ~/nofib/imaginary/wheel-sieve2 1 1 1 >> gennofib.log 2>&1 ;
# stack exec GenesisNF ~/nofib/imaginary/x2n1 1 1 1 >> gennofib.log 2>&1 ;
stack exec GenesisNF ~/nofib/real/PolyGP 1 1 1 >> gennofib.log 2>&1 ;
stack exec GenesisNF ~/nofib/real/anna 1 1 1 >> gennofib.log 2>&1 ;
stack exec GenesisNF ~/nofib/real/cacheprof 1 1 1 >> gennofib.log 2>&1 ;
stack exec GenesisNF ~/nofib/real/compress 1 1 1 >> gennofib.log 2>&1 ;
stack exec GenesisNF ~/nofib/real/compress2 1 1 1 >> gennofib.log 2>&1 ;
stack exec GenesisNF ~/nofib/real/ebnf2ps 1 1 1 >> gennofib.log 2>&1 ;
stack exec GenesisNF ~/nofib/real/fem 1 1 1 >> gennofib.log 2>&1 ;
stack exec GenesisNF ~/nofib/real/fluid 1 1 1 >> gennofib.log 2>&1 ;
stack exec GenesisNF ~/nofib/real/fulsom 1 1 1 >> gennofib.log 2>&1 ;
stack exec GenesisNF ~/nofib/real/gamteb 1 1 1 >> gennofib.log 2>&1 ;
stack exec GenesisNF ~/nofib/real/gg 1 1 1 >> gennofib.log 2>&1 ;
stack exec GenesisNF ~/nofib/real/hidden 1 1 1 >> gennofib.log 2>&1 ;
stack exec GenesisNF ~/nofib/real/infer 1 1 1 >> gennofib.log 2>&1 ;
# stack exec GenesisNF ~/nofib/real/maillist 1 1 1 >> gennofib.log 2>&1 ;
stack exec GenesisNF ~/nofib/real/parser 1 1 1 >> gennofib.log 2>&1 ;
stack exec GenesisNF ~/nofib/real/pic 1 1 1 >> gennofib.log 2>&1 ;
stack exec GenesisNF ~/nofib/real/prolog 1 1 1 >> gennofib.log 2>&1 ;
stack exec GenesisNF ~/nofib/real/reptile 1 1 1 >> gennofib.log 2>&1 ;
stack exec GenesisNF ~/nofib/real/rsa 1 1 1 >> gennofib.log 2>&1 ;
stack exec GenesisNF ~/nofib/real/scs 1 1 1 >> gennofib.log 2>&1 ;
stack exec GenesisNF ~/nofib/real/symalg 1 1 1 >> gennofib.log 2>&1 ;
stack exec GenesisNF ~/nofib/real/veritas 1 1 1 >> gennofib.log 2>&1 ;
# stack exec GenesisNF ~/nofib/shootout/binary-trees 1 1 1 >> gennofib.log 2>&1 ;
# stack exec GenesisNF ~/nofib/shootout/fannkuch-redux 1 1 1 >> gennofib.log 2>&1 ;
# stack exec GenesisNF ~/nofib/shootout/fasta 1 1 1 >> gennofib.log 2>&1 ;
# stack exec GenesisNF ~/nofib/shootout/k-nucleotide 1 1 1 >> gennofib.log 2>&1 ;
# stack exec GenesisNF ~/nofib/shootout/n-body 1 1 1 >> gennofib.log 2>&1 ;
# stack exec GenesisNF ~/nofib/shootout/pidigits 1 1 1 >> gennofib.log 2>&1 ;
stack exec GenesisNF ~/nofib/shootout/reverse-complement 1 1 1 >> gennofib.log 2>&1 ;
stack exec GenesisNF ~/nofib/shootout/spectral-norm 1 1 1 >> gennofib.log 2>&1 ;
# stack exec GenesisNF ~/nofib/spectral/ansi 1 1 1 >> gennofib.log 2>&1 ;
stack exec GenesisNF ~/nofib/spectral/atom 1 1 1 >> gennofib.log 2>&1 ;
stack exec GenesisNF ~/nofib/spectral/awards 1 1 1 >> gennofib.log 2>&1 ;
# stack exec GenesisNF ~/nofib/spectral/banner 1 1 1 >> gennofib.log 2>&1 ;
stack exec GenesisNF ~/nofib/spectral/boyer2 1 1 1 >> gennofib.log 2>&1 ;
stack exec GenesisNF ~/nofib/spectral/calendar 1 1 1 >> gennofib.log 2>&1 ;
stack exec GenesisNF ~/nofib/spectral/cichelli 1 1 1 >> gennofib.log 2>&1 ;
stack exec GenesisNF ~/nofib/spectral/clausify 1 1 1 >> gennofib.log 2>&1 ;
stack exec GenesisNF ~/nofib/spectral/constraints 1 1 1 >> gennofib.log 2>&1 ;
# stack exec GenesisNF ~/nofib/spectral/cryptarithm1 1 1 1 >> gennofib.log 2>&1 ;
# stack exec GenesisNF ~/nofib/spectral/cryptarithm2 1 1 1 >> gennofib.log 2>&1 ;
stack exec GenesisNF ~/nofib/spectral/cse 1 1 1 >> gennofib.log 2>&1 ;
# stack exec GenesisNF ~/nofib/spectral/eliza 1 1 1 >> gennofib.log 2>&1 ;
stack exec GenesisNF ~/nofib/spectral/expert 1 1 1 >> gennofib.log 2>&1 ;
# stack exec GenesisNF ~/nofib/spectral/fish 1 1 1 >> gennofib.log 2>&1 ;
stack exec GenesisNF ~/nofib/spectral/gcd 1 1 1 >> gennofib.log 2>&1 ;
# stack exec GenesisNF ~/nofib/spectral/integer 1 1 1 >> gennofib.log 2>&1 ;
stack exec GenesisNF ~/nofib/spectral/lambda 1 1 1 >> gennofib.log 2>&1 ;
stack exec GenesisNF ~/nofib/spectral/last-piece 1 1 1 >> gennofib.log 2>&1 ;
# stack exec GenesisNF ~/nofib/spectral/lcss 1 1 1 >> gennofib.log 2>&1 ;
stack exec GenesisNF ~/nofib/spectral/life 1 1 1 >> gennofib.log 2>&1 ;
stack exec GenesisNF ~/nofib/spectral/mandel2 1 1 1 >> gennofib.log 2>&1 ;
stack exec GenesisNF ~/nofib/spectral/mate 1 1 1 >> gennofib.log 2>&1 ;
stack exec GenesisNF ~/nofib/spectral/minimax 1 1 1 >> gennofib.log 2>&1 ;
stack exec GenesisNF ~/nofib/spectral/multiplier 1 1 1 >> gennofib.log 2>&1 ;
stack exec GenesisNF ~/nofib/spectral/power 1 1 1 >> gennofib.log 2>&1 ;
stack exec GenesisNF ~/nofib/spectral/pretty 1 1 1 >> gennofib.log 2>&1 ;
# stack exec GenesisNF ~/nofib/spectral/puzzle 1 1 1 >> gennofib.log 2>&1 ;
stack exec GenesisNF ~/nofib/spectral/scc 1 1 1 >> gennofib.log 2>&1 ;
stack exec GenesisNF ~/nofib/spectral/simple 1 1 1 >> gennofib.log 2>&1 ;
stack exec GenesisNF ~/nofib/spectral/sorting 1 1 1 >> gennofib.log 2>&1 ;
stack exec GenesisNF ~/nofib/spectral/treejoin 1 1 1 >> gennofib.log 2>&1 ;
stack exec GenesisNF ~/nofib/spectral/triangle 1 1 1 >> gennofib.log 2>&1  
